name: armazen357
recipe: laravel
config:
  php: '8.4'
  webroot: backend/public
  via: nginx
  database: mysql:8.0

services:
  appserver:
    type: php:8.4
    ssl: true
    overrides:
      environment:
        COMPOSER_MEMORY_LIMIT: -1

  node:
    type: node:20
    ssl: false
    healthcheck: false
    app_mount: false
    overrides:
      volumes:
        - ./frontend:/app/frontend
      working_dir: /app/frontend

tooling:
  composer:
    service: appserver
    cmd: composer
    dir: /app/backend

  php:
    service: appserver
    cmd: php
    dir: /app/backend

  artisan:
    service: appserver
    cmd: php artisan
    dir: /app/backend

  migrate:
    service: appserver
    cmd: php artisan migrate
    dir: /app/backend

  rollback:
    service: appserver
    cmd: php artisan migrate:rollback --step=1
    dir: /app/backend

  tinker:
    service: appserver
    cmd: php artisan tinker
    dir: /app/backend

  install:
    service: appserver
    cmd:
      - composer install --no-cache --working-dir=/app/backend
      - php -r "file_exists('/app/backend/.env') || copy('/app/backend/.env.example', '/app/backend/.env');"
      - php /app/backend/artisan key:generate
      - php /app/backend/artisan migrate --seed
      - php /app/backend/artisan storage:link
    dir: /app/backend

  npm:
    service: node
    cmd: npm
    dir: /app/frontend

  nuxt:
    service: node
    cmd: npx nuxi
    dir: /app/frontend
